/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Controller(props) {
  const { nodes, materials } = useGLTF("/models/controller.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_0.geometry}
        material={materials.material_0}
        position={[-8.432, 0.21, 0.495]}
        scale={0.019}
      />
    </group>
  );
}

useGLTF.preload("/models/controller.glb");
